#!/bin/bash

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

### BEGIN INIT INFO
# Provides:          frocate
# Required-Start:    $local_fs $network
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Jetty with Frocate weabpp
# Description:       Jetty with Frocate weabpp
### END INIT INFO

iptables -t nat -F
iptables -A PREROUTING -t nat -i ens3 -p tcp --dport 80 -j REDIRECT --to-port 8080
/opt/frocate/bin/frocate.sh "$@"
