FROM ubuntu:16.04

#Create user 'test'
RUN adduser --disabled-login -gecos "" test

#Prevent error messages about TERM not available to ask questions during installation
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update

#Workaround - apt-utils are used to ask questions during installation and missing by default in 16.04
#we need to run the command twice cause first time package cannot configure itself yet
RUN apt-get install -y apt-utils
RUN apt-get install -y apt-utils

#Install ifconfig, ping and netcat - useful for tests and debuging
RUN apt-get install -y net-tools
RUN apt-get install -y iputils-ping
RUN apt-get install -y netcat

#Install text tools
RUN apt-get install -y less
RUN apt-get install -y nano

#todo hotfix for 404 not found - seems some caching problem with apt-get update happens in between
RUN apt-get update

#Install add-apt-repository - to install java
RUN apt-get install -y software-properties-common

#Install Oracle JDK 8
RUN add-apt-repository ppa:webupd8team/java -y
RUN apt-get update
RUN echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | debconf-set-selections
RUN apt-get install -y oracle-java8-installer

#Install 'killall' command
RUN apt-get install -y psmisc

USER test
WORKDIR /home/test
